export const resources = {
  en: {
    translation: {
      appName: "ONEBALANCE",
      tagline: "All blockchains as one balance",
      oneBalance: "ONE BALANCE",
      balanceSubtitle: "All your assets (USD)",
      login: "Login",
      register: "Register",
      continue: "Continue",
      loading: "Loading...",
      encrypted: "End-to-end encrypted session",
      securityCenter: "Security Center",
      language: "Language",
      connectedWallets: "Connected Wallets",
      comingSoon: "COMING SOON",
      brandTagline: "One balance, made for you",
      welcomeTitle: "Welcome back",
      welcomeSubtitle: "Sign in to see all your assets in one warm, simple view.",
      getStarted: "Get Started",
      quickEnter: "SIGN IN",
      quickEnterHint: "Passwordless — development mode",
      quickEnterError: "Sign in failed. Refresh and try again.",
      emptyWalletHint: "No wallet connected yet. Connect to see your unified balance.",
      previewMode: "Preview — sample portfolio",
      previewTokensHint: "Connect a wallet for live balances.",
      spendableBalance: "Spendable balance",
      tokens: "Tokens",
      myWallets: "My Wallets",
      operationsMenu: "Operations menu",
      manageWallets: "Manage Wallets",
      dashboard: "Dashboard",
      send: "Send",
      receive: "Receive",
      history: "History",
      riskScore: "Risk Score",
      emergencyDisconnect: "Emergency Disconnect",
      connectedSites: "Connected Websites",
      activeApprovals: "Active Approvals",
      recentActivity: "Recent Activity",
      permissions: "Wallet Permissions",
      connectWallet: "Connect Wallet",
      disconnect: "Disconnect",
      chainMismatch: "Network mismatch detected",
      unknownConnection: "Unknown connection attempt",
      settings: "Settings",
      paymentSuccess: "Payment Successful",
      onboardingStep1: "Secure your account",
      onboardingStep2: "Connect your wallets",
      onboardingStep3: "View your one balance"
    }
  },
  tr: {
    translation: {
      appName: "ONEBALANCE",
      tagline: "Tüm blockchainler tek bakiye",
      oneBalance: "TEK BAKİYE",
      balanceSubtitle: "Tüm varlıklarınız (USD)",
      login: "Giriş",
      register: "Kayıt Ol",
      continue: "Devam",
      loading: "Yükleniyor...",
      encrypted: "Uçtan uca şifreli oturum",
      securityCenter: "Güvenlik Merkezi",
      language: "Dil",
      connectedWallets: "Bağlı Cüzdanlar",
      comingSoon: "ÇOK YAKINDA",
      brandTagline: "Tek bakiye, senin için",
      welcomeTitle: "Tekrar hoş geldin",
      welcomeSubtitle: "Giriş yap; tüm varlıklarını sıcak ve sade bir ekranda gör.",
      getStarted: "Başla",
      quickEnter: "GİRİŞ",
      quickEnterHint: "Şifresiz — geliştirme modu",
      quickEnterError: "Giriş yapılamadı. Sayfayı yenileyip tekrar dene.",
      emptyWalletHint: "Henüz cüzdan bağlamadın. Tek bakiyeni görmek için bağla.",
      previewMode: "Önizleme — örnek portföy",
      previewTokensHint: "Canlı bakiye için cüzdan bağlayın.",
      spendableBalance: "Harcanabilir bakiye",
      tokens: "Token'lar",
      myWallets: "Cüzdanlarım",
      operationsMenu: "İşlemler menüsü",
      manageWallets: "Cüzdanları Yönet",
      dashboard: "Ana Sayfa",
      send: "Gönder",
      receive: "Al",
      history: "Geçmiş",
      riskScore: "Risk Skoru",
      emergencyDisconnect: "Acil Bağlantı Kes",
      connectedSites: "Bağlı Siteler",
      activeApprovals: "Aktif Onaylar",
      recentActivity: "Son Aktivite",
      permissions: "Cüzdan İzinleri",
      connectWallet: "Cüzdan Bağla",
      disconnect: "Bağlantıyı Kes",
      chainMismatch: "Ağ uyumsuzluğu tespit edildi",
      unknownConnection: "Bilinmeyen bağlantı denemesi",
      settings: "Ayarlar",
      paymentSuccess: "Ödeme Başarılı",
      onboardingStep1: "Hesabınızı güvene alın",
      onboardingStep2: "Cüzdanlarınızı bağlayın",
      onboardingStep3: "Tek bakiyenizi görün"
    }
  }
} as const;
